
Sub bplot()

Dim sstext As AcadSelectionSet
Dim filtert(0) As Integer
Dim b As Integer
Dim c As Integer
Dim filterd(0) As Variant
Dim pos1 As Integer
Dim pos2 As Integer
Dim pos As Integer
Dim cadpth As String
Dim pth As String
Dim objDoc As AutoCAD.AcadDocument
 
Dim pdfpth As String

Dim h As String
Dim nh As String
Dim daima2 As String

Dim daima As String
Dim hs As String


Dim exl As New Excel.Application '校对功能
Dim wb As Excel.Workbook
Dim sht As Excel.Worksheet
Dim i As Integer, j As Integer
Dim pickobj As AcadEntity



Set wb = exl.Workbooks.Open("E:\172.16.7.111\1.xlsx")
Set sht = wb.Worksheets("Sheet1")

MyPath = "E:\172.16.7.111\bcg电气零件1\"
MyFile = Dir(MyPath & "*.dwg")
i = 1

Do While MyFile <> ""
pos2 = InStr(MyFile, ".")

pth = Left(MyFile, pos2 - 1)
Set objDoc = Documents.Open(MyPath & MyFile)


For Each pickobj In ThisDrawing.ModelSpace
 If pickobj.ObjectName = "AcDbBlockReference" Then
 If pickobj.HasAttributes Then
  array1 = pickobj.GetAttributes
    If array1(4).TagString = "图样代号" Then
    
      daima2 = array1(4).TextString
      daima = pth
      n = InStrRev(daima, daima2)
      If n = 0 Then
      
      sht.Cells(i, 1) = daima
      i = i + 1
        
     End If
     Exit For
     
     End If
    End If
 End If
On Error Resume Next

Next pickobj


objDoc.Save

objDoc.Close


   
 MyFile = Dir
Loop
wb.Save
 
    wb.Close

    
exl.Quit
End Sub



