
Sub bplot()
'AcadApp.ActiveDocument.ActiveTextStyle.fontFile = "c:\windows\fonts\simsun.ttf"
Dim sstext As AcadSelectionSet

Dim b As Integer
Dim c As Integer

Dim currentpoint As Variant '坐标获取
Dim newpoint(0 To 2) As Double

Dim objDoc As AutoCAD.AcadDocument
 
Dim pdfpth As String
Dim pos As Integer
Dim h As String
Dim nh As String
Dim x As AcadHyperlinks
Dim xh As AcadHyperlink
Dim hs As String
Dim a As Integer

'Dim exl As Excel.Application
'Dim wb As Excel.Workbook
'Dim sht As Excel.Worksheet
Dim i As Integer
Dim pickobj As AcadEntity
Dim array1 As Variant

Dim textobj As AcadText
Dim textstring As String
Dim height As Double
textstring = "481"
height = 3
'Set exl = CreateObject("Excel.Application") '定义excel
'Set wb = exl.Workbooks.Open("E:\BITMAP\" & "bit.xls")
'Set sht = wb.Worksheets("sheet1")

MyPath = "E:\新建文件夹2\"
MyFile = Dir(MyPath & "*.dwg")


Do While MyFile <> ""

Set objDoc = Documents.Open(MyPath & MyFile)


For Each pickobj In ThisDrawing.ModelSpace
nh = pickobj.ObjectName
 If pickobj.ObjectName = "AcDbBlockReference" Then
  If pickobj.Name = "新原理图_模板" Then
  
  currentpoint = pickobj.InsertionPoint
   newpoint(0) = 276 + currentpoint(0) '向右移动100
   newpoint(1) = 11 + currentpoint(1)
   newpoint(2) = 0
ThisDrawing.ActiveTextStyle.fontFile = "c:\windows\fonts\simsun.ttf"

  Set textobj = ThisDrawing.ModelSpace.AddText(textstring, newpoint, height)
  textobj.Update
  
  End If
 End If
On Error Resume Next
  Next pickobj


objDoc.Save

objDoc.Close
MyFile = Dir
Loop

End Sub

