

Sub bplot()

Dim sstext As AcadSelectionSet
Dim filtert(0) As Integer
Dim b As Integer
Dim c As Integer
Dim filterd(0) As Variant

Dim objDoc As AutoCAD.AcadDocument
 
Dim pdfpth As String
Dim pos As Integer
Dim h As String
Dim nh As String

Dim hs As String


'Dim exl As New Excel.Application '校对功能
'Dim wb As Excel.Workbook
'Dim sht As Excel.Worksheet
Dim i As Integer,j As Integer
Dim pickobj As AcadEntity



'Set wb = exl.Workbooks.Open("E:\BITMAP\1.xls")
'Set sht = wb.Worksheets("sheet1")

MyPath = "E:\BITMAP\1\"
MyFile = Dir(MyPath & "*.dwg")
'i = 1

Do While MyFile <> ""
'j = 2
Set objDoc = Documents.Open(MyPath & MyFile)

'sht.Cells(i, 1) = MyFile
'i = i + 1

For Each pickobj In ThisDrawing.ModelSpace
nh = pickobj.ObjectName
 If pickobj.ObjectName = "AcDbAttributeDefinition" Then'这个是2010里的图框
  If pickobj.TagString = "52CBS6020001" Then
  'sht.Cells(i - 1, j) = pickobj.TagString
  'j = j + 1
  pickobj.TagString = "52CBS6020003"
  End If
 End If
On Error Resume Next
  Next pickobj


objDoc.Save

objDoc.Close
MyFile = Dir
Loop

wb.Close

   exl.Quit
End Sub
////////////////////////////////


Sub bplot()

Dim sstext As AcadSelectionSet
Dim filtert(0) As Integer
Dim b As Integer
Dim c As Integer
Dim filterd(0) As Variant

Dim objDoc As AutoCAD.AcadDocument
 
Dim pdfpth As String
Dim pos As Integer
Dim h As String
Dim nh As String

Dim hs As String


Dim exl As New Excel.Application '校对功能
Dim wb As Excel.Workbook
Dim sht As Excel.Worksheet
Dim i As Integer, j As Integer
Dim pickobj As AcadEntity



Set wb = exl.Workbooks.Open("E:\BITMAP\1.xls")
Set sht = wb.Worksheets("sheet1")

MyPath = "E:\BITMAP\位置图新版778.17.0017\"
MyFile = Dir(MyPath & "*.dwg")
i = 1

Do While MyFile <> ""
j = 2
Set objDoc = Documents.Open(MyPath & MyFile)

sht.Cells(i, 1) = MyFile
i = i + 1

For Each pickobj In ThisDrawing.ModelSpace
nh = pickobj.ObjectName
 If pickobj.ObjectName = "AcDbAttributeDefinition" Then '这个是2010里的图框
  If pickobj.TagString = "52CBS6020001" Then
  sht.Cells(i - 1, j) = pickobj.TagString
  j = j + 1
  pickobj.TagString = "52CBS6020003"
  End If
 End If
On Error Resume Next
  Next pickobj


objDoc.Save

objDoc.Close
MyFile = Dir
Loop

wb.Close

   exl.Quit
End Sub



