
Sub bplot()

Dim sstext As AcadSelectionSet


Dim c As Integer


Dim value As String
Dim pro As String
Dim array1 As Variant
Dim blkelem As AcadEntity
Dim objDoc As AutoCAD.AcadDocument
 
Dim pdfpth As String
Dim pos As Integer
Dim h As String
Dim nh As String
Dim bobs As AcadBlocks
Dim bob As AcadBlock
Dim bref As AcadBlockReference

Dim hs As String
Dim a As Integer

Dim exl As Excel.Application
Dim wb As Excel.Workbook
Dim sht As Excel.Worksheet
Dim i As Integer
Dim pickobj As AcadBlock

'Set exl = CreateObject("Excel.Application") '定义excel
'Set wb = exl.Workbooks.Open("E:\BITMAP\bit\" & "xit.xls") '将修改过的文件写入excel
'Set sht = wb.Worksheets("sheet1")

MyPath = "E:\BITMAP\bit\"
MyFile = Dir(MyPath & "*.dwg")


Do While MyFile <> ""

Set objDoc = Documents.Open(MyPath & MyFile)
For Each blkelem In objDoc.ModelSpace
 With blkelem
 If StrComp(.EntityName, "AcDbBlockReference", 1) = 0 Then
  If .HasAttributes Then
 array1 = .GetAttributes
 For i = LBound(array1) To UBound(array1)
   If array1(i).PromptString = "GD图号" Then'这里报错 不知道为什么
    value = array1(i).TextString
    Exit For
   End If
 Next i
 End If
 End If
 End With
Next blkelem

On Error Resume Next
If value <> "" Then
objDoc.SaveAs (value)
End If

objDoc.Close
MyFile = Dir
Loop

wb.Close
End Sub
//////////////////////////////////最后使用这个程序指定块属性

Sub bplot()

Dim sstext As AcadSelectionSet

Dim filtert(0) As Integer
Dim filterd(0) As Variant
Dim c As Integer


Dim value As String
Dim pro As String
Dim array1 As Variant 'AcadBlockReference
Dim blkelem As AcadEntity
Dim objDoc As AutoCAD.AcadDocument
 
Dim pdfpth As String
Dim pos As Integer
Dim h As String
Dim nh As String
Dim bobs As AcadBlocks
Dim bob As AcadBlock


Dim hs As String
Dim a As Integer

Dim i As Integer
Dim pickobj As AcadBlock


MyPath = "E:\BITMAP\bit\"
MyFile = Dir(MyPath & "*.dwg")


Do While MyFile <> ""

Set objDoc = Documents.Open(MyPath & MyFile)
'Set sstext = objDoc.SelectionSets.Add("ss")
'filtert(0) = 0
'filterd(0) = "INSERT"
'sstext.Select acSelectionSetAll, , , filtert, filterd
For Each blkelem In ThisDrawing.ModelSpace
 With blkelem
 If StrComp(.EntityName, "AcDbBlockReference", 1) = 0 Then
  If .HasAttributes Then
  
array1 = .GetAttributes
hs = array1(3).TextString'第一位是0
  If hs <> "" Then
    value = array1(3).TextString
   
   End If
   

 End If
 End If
 End With
Next blkelem

On Error Resume Next
If value <> "" Then
objDoc.SaveAs (MyPath & value & ".dwg")'指定文件夹和文件名
End If

objDoc.Close
MyFile = Dir
Loop

wb.Close
End Sub
