

Sub bplot()

Dim sstext As AcadSelectionSet
Dim filtert(0) As Integer
Dim b As Integer
Dim c As Integer
Dim filterd(0) As Variant

Dim objDoc As AutoCAD.AcadDocument
 
Dim pdfpth As String
Dim pos As Integer
Dim h As String
Dim nh As String
Dim x As AcadHyperlinks
Dim xh As AcadHyperlink
Dim hs As String
Dim a As Integer

'Dim exl As Excel.Application
'Dim wb As Excel.Workbook
'Dim sht As Excel.Worksheet
Dim i As Integer
Dim pickobj As AcadEntity


'Set exl = CreateObject("Excel.Application") '定义excel
'Set wb = exl.Workbooks.Open("E:\BITMAP\" & "bit.xls")
'Set sht = wb.Worksheets("sheet1")

MyPath = "E:\BITMAP\alone cv\"
MyFile = Dir(MyPath & "*.dwg")


Do While MyFile <> ""

Set objDoc = Documents.Open(MyPath & MyFile)
Set sstext = objDoc.SelectionSets.Add("ss")
filtert(0) = 0
filterd(0) = "MTEXT"'如果是单行字就是TEXT
sstext.Select acSelectionSetAll, , , filtert, filterd

For Each pickobj In sstext
 If pickobj.ObjectName = "AcDbMText" Then'如果是单行字就是AcDbText
  hs = pickobj.TextString
  If hs = "{\f仿宋_GB2312|b0|i0|c134|p49;连卢}" Then
   pickobj.TextString = "{\f仿宋_GB2312|b0|i0|c134|p49;六蛮}"
  End If
  If hs = "{\fSimSun|b0|i0|c134|p2; }" Then '不同字体需要f8单步调试
  pickobj.TextString = "{\f仿宋_GB2312|b0|i0|c134|p49;きキ}"
  End If
 End If
 
  Next pickobj

On Error Resume Next
objDoc.Save

objDoc.Close
MyFile = Dir
Loop

End Sub

//////////////////////////////////////////////



Sub bplot()

Dim sstext As AcadSelectionSet
Dim filtert(0) As Integer
Dim b As Integer
Dim c As Integer
Dim filterd(0) As Variant

Dim objDoc As AutoCAD.AcadDocument
 
Dim pdfpth As String
Dim pos As Integer
Dim h As String
Dim nh As String
Dim x As AcadHyperlinks
Dim xh As AcadHyperlink
Dim hs As String
Dim a As Integer

'Dim exl As Excel.Application
'Dim wb As Excel.Workbook
'Dim sht As Excel.Worksheet
Dim i As Integer
Dim pickobj As AcadEntity
Dim array1 As Variant

'Set exl = CreateObject("Excel.Application") '定义excel
'Set wb = exl.Workbooks.Open("E:\BITMAP\" & "bit.xls")
'Set sht = wb.Worksheets("sheet1")


MyPath = "E:\BITMAP\alone\"
MyFile = Dir(MyPath & "*.dwg")



Do While MyFile <> ""

Set objDoc = Documents.Open(MyPath & MyFile)


For Each pickobj In ThisDrawing.ModelSpace
 If pickobj.ObjectName = "AcDbBlockReference" Then
 If pickobj.HasAttributes Then
  array1 = pickobj.GetAttributes
 array1(5).TextString = "20120420"
 array1(1).TextString = "独立运行条外透明纸包装机"
 array1(1).ScaleFactor = 0.95 '修改字符间距
 array1(7).TextString = "52CCE4040100"
  End If
 End If
On Error Resume Next
  Next pickobj


objDoc.Save

objDoc.Close
MyFile = Dir
Loop

End Sub
////////////////////////////////////////最终版 有校对功能




Sub bplot()

Dim sstext As AcadSelectionSet
Dim filtert(0) As Integer
Dim b As Integer
Dim c As Integer
Dim filterd(0) As Variant

Dim objDoc As AutoCAD.AcadDocument
 
Dim pdfpth As String
Dim pos As Integer
Dim h As String
Dim nh As String
Dim x As AcadHyperlinks
Dim xh As AcadHyperlink
Dim hs As String
Dim a As Integer

Dim exl As New Excel.Application'使用excel记录
Dim wb As Excel.Workbook
Dim sht As Excel.Worksheet
Dim i As Integer, j As Integer, n As Integer
Dim pickobj As AcadEntity



Set wb = exl.Workbooks.Open("E:\BITMAP\1.xls")
Set sht = wb.Worksheets("sheet1")


MyPath = "E:\BITMAP\1\"
MyFile = Dir(MyPath & "*.dwg")

i = 1

Do While MyFile <> ""
j = 2
Set objDoc = Documents.Open(MyPath & MyFile)
sht.Cells(i, 1) = MyFile
i = i + 1
Set sstext = objDoc.SelectionSets.Add("ss")
filtert(0) = 0
filterd(0) = "MTEXT"
sstext.Select acSelectionSetAll, , , filtert, filterd

For Each pickobj In sstext
 If pickobj.ObjectName = "AcDbMText" Then
  hs = pickobj.TextString
  If hs = "{\f仿宋_GB2312|b0|i0|c134|p49;连卢}" Then
   pickobj.TextString = "{\f仿宋_GB2312|b0|i0|c134|p49;六蛮}"
  End If
  If hs = "{\f仿宋_GB2312|b0|i0|c134|p49; }" Then'这个名字如果找不到 则需要f8单步调试看下hs的值
  pickobj.TextString = "{\f仿宋_GB2312|b0|i0|c134|p49;癔虔}"
  sht.Cells(i - 1, j) = hs
 j = j + 1
  End If
 End If
 
  Next pickobj

On Error Resume Next
objDoc.Save


objDoc.Close

MyFile = Dir
Loop
wb.Save
wb.Close
exl.Quit
End Sub



