

Sub bplot()

Dim sstext As AcadSelectionSet
Dim filtert(0) As Integer
Dim b As Integer
Dim c As Integer
Dim filterd(0) As Variant

Dim objDoc As AutoCAD.AcadDocument
 
Dim pdfpth As String
Dim pos As Integer
Dim h As String
Dim nh As String
Dim x As AcadHyperlinks
Dim xh As AcadHyperlink
Dim hs As String
Dim a As Integer

'Dim exl As Excel.Application
'Dim wb As Excel.Workbook
'Dim sht As Excel.Worksheet
Dim i As Integer
Dim pickobj As AcadEntity
Dim array1 As Variant

'Set exl = CreateObject("Excel.Application") '定义excel
'Set wb = exl.Workbooks.Open("E:\BITMAP\" & "bit.xls")
'Set sht = wb.Worksheets("sheet1")

MyPath = "E:\BITMAP\"
MyFile = Dir(MyPath & "*.dwg")


Do While MyFile <> ""

Set objDoc = Documents.Open(MyPath & MyFile)


For Each pickobj In thisdrawing.modelspace
 If pickobj.ObjectName = "AcDbBlockReference" Then
 If pickobj.HasAttributes Then
  array1 = pickobj.GetAttributes
 array1(5).TextString = "2012"
  End If
 End If
On Error Resume Next
  Next pickobj


objDoc.Save

objDoc.Close
MyFile = Dir
Loop

End Sub
///////////////////////////////////带校验功能的最终版


Sub bplot()

Dim sstext As AcadSelectionSet
Dim filtert(0) As Integer
Dim b As Integer
Dim c As Integer
Dim filterd(0) As Variant

Dim objDoc As AutoCAD.AcadDocument
 
Dim pdfpth As String
Dim pos As Integer
Dim h As String
Dim nh As String

Dim hs As String
Dim array1 As Variant

Dim exl As New Excel.Application '校对功能
Dim wb As Excel.Workbook
Dim sht As Excel.Worksheet
Dim i As Integer, j As Integer
Dim pickobj As AcadEntity



Set wb = exl.Workbooks.Open("E:\BITMAP\1.xls")
Set sht = wb.Worksheets("sheet1")

MyPath = "E:\BITMAP\52BCS4040003\"
MyFile = Dir(MyPath & "*.dwg")
i = 1

Do While MyFile <> ""
j = 2
Set objDoc = Documents.Open(MyPath & MyFile)

sht.Cells(i, 1) = MyFile
i = i + 1

For Each pickobj In ThisDrawing.ModelSpace

 If pickobj.ObjectName = "AcDbBlockReference" Then '这个是2010里的图框
  If pickobj.HasAttributes Then
  array1 = pickobj.GetAttributes
    If array1(7).TextString = "52BCS4040001" Then
      sht.Cells(i - 1, j) = array1(7).TextString
     j = j + 1
     array1(7).TextString = "52BCS4040003"
    End If
  End If
 End If
 
On Error Resume Next
  Next pickobj


objDoc.Save

objDoc.Close
MyFile = Dir
Loop

wb.Close
exl.Quit
End Sub


